package Vista;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.vo.primerInformeVo;
import model.vo.segundoInformeVo;
import model.vo.tercerInformeVo;
import Controlador.controladorReportes;
import static Vista.vistaInformes.controlador;;


public class Consultas extends javax.swing.JFrame{

    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;


    
public Consultas() throws java.sql.SQLException {

    initComponents();
    actualizarTabla();

}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents

private void initComponents() {

    //Botones y espacios requeridos para cada consulta

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jSplitPane1 = new javax.swing.JSplitPane();
    jPanel4 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jPanel2 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jSplitPane2 = new javax.swing.JSplitPane();
    jPanel6 = new javax.swing.JPanel();
    jPanel7 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2 = new javax.swing.JTable();
    jPanel3 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jSplitPane3 = new javax.swing.JSplitPane();
    jPanel8 = new javax.swing.JPanel();
    jPanel9 = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTable3 = new javax.swing.JTable();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();
    jMenuItem4 = new javax.swing.JMenuItem();

//Titulo menu desplegable
    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Consultas");

    jPanel1.setLayout(new java.awt.BorderLayout());

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    //Descripcion espacio del primer informe

    jLabel1.setText("Información respectiva al Líder.");
    jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

    jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 785, Short.MAX_VALUE)
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    jSplitPane1.setTopComponent(jPanel4);

    jPanel5.setLayout(new java.awt.BorderLayout());

    //Esquema de la tabla a mostras para el primer informe
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "ID_Lider", "Nombre", "Primer_Apellido", "Ciudad_Residencia"
        }
    ));

    jScrollPane1.setViewportView(jTable1);

    jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

    jSplitPane1.setRightComponent(jPanel5);

    jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("Primer Informe", jPanel1);

    jPanel2.setLayout(new java.awt.BorderLayout());

    jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

    //Descripcion del espacio para el segundo informe

    jLabel2.setText("información de los proyectos cuya clasificación sea "
    +"Casa Campestre y que estén ubicados en las ciudades de Santa Marta, Cartagena y "
    +"Barranquilla. ");
    jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

    jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 785, Short.MAX_VALUE)
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    jSplitPane2.setTopComponent(jPanel6);

    jPanel7.setLayout(new java.awt.BorderLayout());

    //Esquema de la tabla en el segundo informe

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "ID_Proyecto", "Constructora", "Nùmero_Habitaciones", "Ciudad"
        }
    ));
    jScrollPane2.setViewportView(jTable2);

    jPanel7.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    jSplitPane2.setRightComponent(jPanel7);

    jPanel2.add(jSplitPane2, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("Segundo Informe", jPanel2);

//Descripcion espacio para el tercer informe

    jPanel3.setLayout(new java.awt.BorderLayout());

    jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("compras realizadas por los proyectos con el proveedor "
    +"Homecenter y para la ciudad Salento.");
    jPanel3.add(jLabel3, java.awt.BorderLayout.PAGE_START);

    jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 785, Short.MAX_VALUE)
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    jSplitPane3.setTopComponent(jPanel8);

    jPanel9.setLayout(new java.awt.BorderLayout());

//Esquema tabla a mostrar para el tercer informe

    jTable3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null},
            {null, null, null},
            {null, null, null},
            {null, null, null}
        },
        new String [] {
            "ID_Compra", "Constructora", "Banco_Vinculado"
        }
    ));
    jScrollPane3.setViewportView(jTable3);

    jPanel9.add(jScrollPane3, java.awt.BorderLayout.CENTER);

    jSplitPane3.setRightComponent(jPanel9);

    jPanel3.add(jSplitPane3, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("Tercer Informe", jPanel3);

    getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

//Aunque hay botones de acceso a cada consulta, se incluye un menu desplegable con acceso a cada consulta

    jMenu1.setText("Consultas");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem1.setText("Primer Informe");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem2.setText("Segundo Informe");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem3.setText("Tercer Informe");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItem3);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Salir");

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem4.setText("Salir");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItem4);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    pack();


}

public void actualizarTabla() throws SQLException {

    // Actualizar vista tabla primer informe        
            ArrayList<primerInformeVo> primerinforme = controlador.consultarPrimerInforme();            
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            
            while (modelo.getRowCount() > 0 ) {
                modelo.removeRow(0);
            }
            int numcols = modelo.getColumnCount();
            for (primerInformeVo requerimiento : primerinforme) {
               Object[] fila = new Object[numcols];
               
//
fila[0]=requerimiento.getIdLider();
fila[1]=requerimiento.getNombre();
fila[2]=requerimiento.getPrimerApellido();
fila[3]=requerimiento.getCiudadResidencia();

               
               modelo.addRow(fila);
               
            }

// Actualizar vista tabla segundo informe       
ArrayList<segundoInformeVo> segundoinforme = controlador.consultarSegundoInforme();
        
modelo = (DefaultTableModel) jTable2.getModel();

while (modelo.getRowCount() > 0 ) {
    modelo.removeRow(0);
}
numcols = modelo.getColumnCount();
for (segundoInformeVo requerimiento : segundoinforme) {
   Object[] fila = new Object[numcols];
   

   fila[0]=requerimiento.getIdProyecto();
   fila[1]=requerimiento.getConstructora();
fila[2]=requerimiento.getNumeroHabitaciones();
fila[3]=requerimiento.getCiudad();

   modelo.addRow(fila);
   
}

// Actualizar vista tabla tercer informe       
ArrayList<tercerInformeVo> tercerinforme = controlador.consultarTercerInforme();

modelo = (DefaultTableModel) jTable3.getModel();

while (modelo.getRowCount() > 0 ) {
    modelo.removeRow(0);
}
numcols = modelo.getColumnCount();
for (tercerInformeVo requerimiento : tercerinforme) {
   Object[] fila = new Object[numcols];
   


   fila[0]=requerimiento.getIdCompra();
   fila[1]=requerimiento.getConstructora();
   fila[2]=requerimiento.getBancoVinculado();
     
   modelo.addRow(fila);
   
}




}

//acciones para disparar los eventos principales

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(0);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(1);
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    // TODO add your handling code here:
    jTabbedPane1.setSelectedIndex(2);
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    // TODO add your handling code here:
    if (JOptionPane.showConfirmDialog(this, "Desea cerrar la aplicación?", 
            getTitle(), JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)== JOptionPane.YES_OPTION) {
        dispose();
    }
}//GEN-LAST:event_jMenuItem4ActionPerformed

/**
 * @param args the command line arguments
 */


//Ya que se ha incluido un modo consola, en esta clase se ejecutara el GUI por facilidad de seguimiento
//Es posible modificar el valor de cualquier casilla, pero al no espacificar el salvado, tal cambio es ignorado al cerrar
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                new Consultas().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    });
}



}
